mysql:
  host: localhost
  port: 3306
  username: root
  password: p@ssword
  database: data

settings:
  # Set the amount of crates a player can open each day
  per-day: 3
  # Set the cooldown which a player has to wait between opening crates,
  # time unit is seconds.
  cooldown: 5